### ISSUE TITLE
Keep the same theme for the head of all page, but no login button after login or change login button to logout after login

### ISSUE THREAD

**Issue by feiyanzhandui** [0xdyu/KD#19]

**Comment by dorismeixing** [comment]
The theme is same for the head of all pages now.

Here is the new problem I found:
After the user logs in the system, the main page will have show up the "登陆“ button if he/she to goes back to ”首页“. Need to create a IF loop here. The IF loop should let the main page to show "Log out" if the user logs in, otherwise shows "登陆”。

**Comment by dorismeixing** [comment]
The home page still show the "登陆“ button even after the use has logged in. Assign it to 小坏.

**Comment by feiyanzhandui** [comment]
done
